// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEA3GuLtbgHzScynaF-38JiUnrhAlzdnI',
    appId: '1:91948282855:web:019cd277ab1b8e74784342',
    messagingSenderId: '91948282855',
    projectId: 'energy-visualizer-7c22f',
    authDomain: 'energy-visualizer-7c22f.firebaseapp.com',
    storageBucket: 'energy-visualizer-7c22f.firebasestorage.app',
    measurementId: 'G-KJJ9YL1FJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxnGICX7aGc1aeq3phGLYrAHfNZmvIqWc',
    appId: '1:91948282855:android:fad8c8072921cae6784342',
    messagingSenderId: '91948282855',
    projectId: 'energy-visualizer-7c22f',
    storageBucket: 'energy-visualizer-7c22f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgr0vJB06WAsWFNyoqw7xAOnmzASHKEcE',
    appId: '1:91948282855:ios:51fa1fda08925051784342',
    messagingSenderId: '91948282855',
    projectId: 'energy-visualizer-7c22f',
    storageBucket: 'energy-visualizer-7c22f.firebasestorage.app',
    iosBundleId: 'com.example.energyVisualizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgr0vJB06WAsWFNyoqw7xAOnmzASHKEcE',
    appId: '1:91948282855:ios:51fa1fda08925051784342',
    messagingSenderId: '91948282855',
    projectId: 'energy-visualizer-7c22f',
    storageBucket: 'energy-visualizer-7c22f.firebasestorage.app',
    iosBundleId: 'com.example.energyVisualizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEA3GuLtbgHzScynaF-38JiUnrhAlzdnI',
    appId: '1:91948282855:web:625306bd26b06d6a784342',
    messagingSenderId: '91948282855',
    projectId: 'energy-visualizer-7c22f',
    authDomain: 'energy-visualizer-7c22f.firebaseapp.com',
    storageBucket: 'energy-visualizer-7c22f.firebasestorage.app',
    measurementId: 'G-NWVK8ER3BM',
  );
}
